### ISSUE TITLE
Saut de lignes ignorées

### ISSUE THREAD

**Issue by aploon** [D3R50N/text-checker#1]
Lorsqu'on clique sur "check difference" les sauts de ligne n'apparaissent plus et tout revient sur la même ligne
ça ne permet pas d'apprécier les différences sur chaque ligne de code

**Comment by D3R50N** [comment]
En effet, j'essayerai d'arranger ça au plus vite.

**Comment by D3R50N** [comment]
Problème résolu.

**Comment by aploon** [comment]
Cool, ça marche
